[build]
  publish = "dist/blog-creditos"
  command = "npm install -g @angular/cli && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NG_CLI_ANALYTICS = "false"
  NODE_ENV = "development"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"